FROM gcc:latest

# GET ARGS
ARG ODASA_TRACER_CONFIGURATION
ARG CODEQL_SCRATCH_DIR
ARG CODEQL_DIST
ARG CODEQL_PLATFORM
ARG CODEQL_PLATFORM_DLL_EXTENSION
ARG CODEQL_JAVA_HOME
ARG CODEQL_EXTRACTOR_CPP_ROOT
ARG CODEQL_EXTRACTOR_CPP_WIP_DATABASE
ARG CODEQL_EXTRACTOR_CPP_LOG_DIR
ARG CODEQL_EXTRACTOR_CPP_SCRATCH_DIR
ARG CODEQL_EXTRACTOR_CPP_TRAP_DIR
ARG CODEQL_EXTRACTOR_CPP_SOURCE_ARCHIVE_DIR
ARG LD_PRELOAD

# SET ENV
ENV \
    ODASA_TRACER_CONFIGURATION=${ODASA_TRACER_CONFIGURATION} \
    CODEQL_SCRATCH_DIR=${CODEQL_SCRATCH_DIR} \
    CODEQL_DIST=${CODEQL_DIST} \
    CODEQL_PLATFORM=${CODEQL_PLATFORM} \
    CODEQL_PLATFORM_DLL_EXTENSION=${CODEQL_PLATFORM_DLL_EXTENSION} \
    CODEQL_JAVA_HOME=${CODEQL_JAVA_HOME} \
    CODEQL_EXTRACTOR_CPP_ROOT=${CODEQL_EXTRACTOR_CPP_ROOT} \
    CODEQL_EXTRACTOR_CPP_WIP_DATABASE=${CODEQL_EXTRACTOR_CPP_WIP_DATABASE} \
    CODEQL_EXTRACTOR_CPP_LOG_DIR=${CODEQL_EXTRACTOR_CPP_LOG_DIR} \
    CODEQL_EXTRACTOR_CPP_SCRATCH_DIR=${CODEQL_EXTRACTOR_CPP_SCRATCH_DIR} \
    CODEQL_EXTRACTOR_CPP_TRAP_DIR=${CODEQL_EXTRACTOR_CPP_TRAP_DIR} \
    CODEQL_EXTRACTOR_CPP_SOURCE_ARCHIVE_DIR=${CODEQL_EXTRACTOR_CPP_SOURCE_ARCHIVE_DIR} \
    LD_PRELOAD=${LD_PRELOAD}

COPY . .

RUN . ./bmenv.sh && make rebuild
